config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sign_up'

  devise_for :users

  resources :users, only: [:show]

  resources :wikis do
    resources :collaborators, only: [:create, :destroy, :index]
  end
  
  resources :charges, only: [:new, :create, :destroy]

  root 'wikis#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base

  def self.default
  	10_00
  end

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base

	belongs_to :user 
	belongs_to :wiki 
	# Should dependent: :destroy add on be applied here?

  def self.users
  	User.where(id: pluck(:user_id))
  end

  def self.wikis
  	Wiki.where(id: pluck(:wiki_id))
  end

  def wiki
  	Wiki.find(wiki_id)
  end

  def user
  	User.find(user_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
has_many :wikis, dependent: :nullify

before_save do 
	self.email = email.downcase
end

after_initialize :defaults

def defaults
	self.role ||= :standard	#self.role = :standard if self.role.nil?
end

def downgrading_wikis!
  wikis.update_all(private: false)
end

def collaborators
  Collaborator.where(user_id: id)
end

def collaborated_wikis
	collaborators.map(&:wiki)
end

def all_wikis
	wikis + collaborated_wikis
end

# def wikis
#   # Wiki.where( id: collaborators.pluck(:wiki_id))
#   collaborators.wikis
# end

  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable



  enum role: [:standard, :premium, :admin]



end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :publicly_viewable, -> {where(private: false || nil)}

  def public?
    !private
  end

  def collaborator_for(user)
  	collaborators.where(user: user).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  include Pundit

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  	wikis_path
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


	 def new
	   @stripe_btn_data = {
	     key: "#{ Rails.configuration.stripe[:publishable_key] }",
	     description: "Premium Plan - #{current_user.name}",
	     amount: Amount.default
	   }
	 end

	 def create
	 
		   # Creates a Stripe Customer object, for associating
		   # with the charge
		   customer = Stripe::Customer.create(
		     email: current_user.email,
		     card: params[:stripeToken]
		   )
		 
		   # Where the real magic happens
		   charge = Stripe::Charge.create(
		     customer: customer.id, # Note -- this is NOT the  user_id in your app
		     amount: Amount.default,
		     description: "Premium Plan - #{current_user.email}",
		     currency: 'usd'
		   )

		   current_user.premium!
		 
		   flash[:notice] = "Thank you #{current_user.name}! Your payment was processed!"
		   redirect_to user_path(current_user) # or wherever
		 
		 # Stripe will send back CardErrors, with friendly messages
		 # when something goes wrong.
		 # This `rescue block` catches and displays those errors.
		 rescue Stripe::CardError => e
		   flash.now[:alert] = e.message
		   redirect_to new_charge_path

	 end


	 def destroy

		   current_user.standard!
		   current_user.downgrading_wikis!
		 
		   flash[:notice] = "#{current_user.name}, your account has now been downgraded."
		   redirect_to user_path(current_user)


	 end



end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
	before_action :set_wiki

	def index
		@users = User.all
	end

	def create

		@collaborator = @wiki.collaborators.new(user_id: params[:user_id])

		if @collaborator.save
 			flash[:notice] = "You added a collaborator"
 		else
 			flash[:error] = "There was an error"
 		end

			redirect_to wiki_collaborators_path(@wiki)

		# respond_to do |format|
		# 	format.html
		# 	format.js
		# end

	end

	def destroy

 		@collaborator = Collaborator.find(params[:id])
 		if @collaborator.destroy
 			flash[:notice] = "You removed a collaborator"
 		else
 			flash[:error] = "There was an error"
 		end

			redirect_to wiki_collaborators_path(@wiki)

 		# respond_to do |format|
 		# 	format.html
 		# 	format.js
 		# end


	end

	private

	def set_wiki
		@wiki = Wiki.find(params[:wiki_id])
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    skip_before_action :authenticate_user!

  def sign_up
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

	#before_actions.....

	def index

	  @wikis = policy_scope(Wiki)

	end

	def show

	  @wiki = Wiki.find(params[:id])
	  authorize @wiki 

	end


	def new

	  @wiki = Wiki.new

	end


	def create

	  # @wiki = Wiki.new
	  # @wiki.title = params[:wiki][:title]
	  # @wiki.body = params[:wiki][:body]
	  # @wiki.public = params[:wiki][:public]
	  # @wiki.user = current_user

	  @wiki = current_user.wikis.new(wiki_params)

	  if @wiki.save
	  	flash[:notice] = "Wiki saved!"
	  else
	  	flash[:error] = "Error... the Wiki was NOT saved!"
	  end

	  redirect_to current_user

	end


	def edit

	  @wiki = Wiki.find(params[:id])

	end


	def update

	  @wiki = Wiki.find(params[:id])
	  @wiki.assign_attributes(wiki_params)

	  if @wiki.save
	  	flash[:notice] = "Wiki updated!"
	  	redirect_to @wiki
	  else
	  	flash[:error] = "Error... the Wiki was NOT updated"
	  	render :edit
	  end

	end


	def destroy

	  @wiki = Wiki.find(params[:id])
	  authorize @wiki

	  if @wiki.destroy
	  	flash[:notice] = "\'#{wiki.title}\' was deleted successfully."
	    redirect_to action: :index
	  else
	  	flash[:error] = "There was an error deleting the wiki."
	  	render :show
	  end

	end

    private

    def wiki_params
    	params.require(:wiki).permit(:title, :body, :private)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
  	if errors.any?
  	  content_tag :div, capture(&block), class: 'form-group has-error'
  	else
  	  content_tag :div, capture(&block), class: 'form-group'
  	end
  end

  def markdown(text)
  	options = {
  		filter_html:  true,
  		hard_wrap: true,
  		link_attributes:  { rel: 'nofollow', target: "_blank" },
  		space_after_headers:  true,
  		fenced_code_blocks: true
  	}

  	extensions = {
  		autolink:  true,
  		superscript:  true,
  		disable_indented_code_blocks:  true
  	}

  	renderer = Redcarpet::Render::HTML.new(options)
  	markdown = Redcarpet::Markdown.new(renderer, extensions)

  	markdown.render(text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' 
   src="https://checkout.stripe.com/checkout.js" 
   data-key="<%= @stripe_btn_data[:key] %>" 
   data-amount=<%= @stripe_btn_data[:amount] %> 
   data-description="<%= @stripe_btn_data[:description] %>" >
   </script>
 <% end %>

app/views/collaborators/create.js.erb
<% if @collaborator.save %>
  $("")

app/views/collaborators/index.html.erb
<div class="col-md-7">

  <br>
  <% if current_user.admin? || current_user.premium? %>
  <h4 class="text-center">Add Collaborators to <br><%= @wiki.title %></h4>
  <br>
  <br>

  <table class="table">

   <tr>
     <th>Name</th>
     <th>Email</th>
     <th>Give Access</th>
   </tr>

   <% @users.each do |u| %>
     <% if u == current_user %>
     <% else %>
     <tr>
       <td><%= u.name %></td>
       <td><%= u.email %></td>
       <% if @wiki.users.include?(u) %>
         <td><%= link_to "", wiki_collaborator_path(@wiki, @wiki.collaborator_for(u)), method: :delete, class: 'glyphicon glyphicon-check' %></td>
       <% else %>
  		   <td><%= link_to "", wiki_collaborators_path(@wiki, user_id: u.id ), method: :post, class: 'glyphicon glyphicon-unchecked' %></td>
       <% end %>
     </tr>
     <% end %>
   <% end %>
  <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="container">
  	<div class="pull-right user-info">

      <% if user_signed_in? %>
	    Signed in as: <strong><%= link_to current_user.email, user_path(current_user), :class => 'navbar-link' %>
    </strong> | <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
	    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
      <% end %>

    </div>
    <% if user_signed_in? %>
      <div class="row top-row">
        <div class="col-md-3">
          <p><%= link_to "Blocipedia", wikis_path %></p>
          <p><%= link_to "My Wikis", user_path(current_user) %></p>
          <p>About Blocipedia</p>
          <p>Help</p>
          <p>Contact Page</p>
          <p>Upgrade Account<p>
        </div>
    <% end %>
        <%= yield %>
      </div>

  </div>
  
</body>
</html>

app/views/users/show.html.erb
<div class='col-md-7'>
  <div class="text-center">
    <h1>My Wikis</h1>
    <p>Role - <%= current_user.role.titleize %></p>
    
    <% if current_user.standard? %> 
      <p><%= link_to "Upgrade Account", new_charge_path, class: 'btn btn-default shadow' %><p>
    <% end %>

    <% if current_user.premium? %>
      <p><%= link_to "Downgrade Account", charge_path, method: :delete, class: 'btn btn-danger', data: {confirm: 'If you downgrade your account your private wikis will become public.  Are you sure you want to downgrade your account?'} %>
    <% end %>
    <br>
    <br>

  </div>
    <table class="table">
      <tr>
        <th>Wiki Title</th>
        <th>Edit Wiki</th>
        <% if current_user.admin? %>
          <th>Delete Wiki</th>
        <% end %>
      </tr>
      <% current_user.wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.title, wiki %></td>
        <td><%= link_to "Edit", edit_wiki_path %></td>
        <if current_user.admin? %>
          <td><%= link_to "Delete", @wiki, method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'} %></td>
      <tr>
        <% end %>
    </table>
    <br>
    <br>
    <br>
</div>

<div class='col-md-2'>
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-default' %>
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
</div>

app/views/welcome/sign_up.html.erb
<div class="text-center">
  <h1>Blocipedia: Social, Markdown Wikis</h1>
    <br>
    <br>
    <br>
  <h3>Create and share Markdown Wikis</h1>
    <br>
    <br>
  <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-default btn-lg shadow' %>
    <br>
    <br>

  <div class='row'>
    <div class='col-md-4'>
      Create as many public wikis as you want!
      Create private wikis!
    </div>
  </div>
  <div class='row'>
  	<div class='col-md-4'>
      Button 1
      <%= link_to "Upgrade Account", new_charge_path, class: 'btn btn-default shadow' %>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<div class="col-md-9">
  <%= form_for @wiki do |f| %>
    <% if @wiki.errors.any? %>

      <div class="alert alert-danger">

        <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
        <ul>
        <% @wiki.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_group_tag(@wiki.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
    <% end %>

    <%= form_group_tag(@wiki.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 12, class: 'form-control', placeholder: "Enter Wiki article body" %>
    <% end %>

    <% if current_user.admin? || current_user.premium? %>
      
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private Wiki
        <% end %>
      </div>

    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>

  <% end %>
</div>

<% if current_user.admin? || current_user.premium? %>
  <%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki), class: "btn btn-info" %>
<% end %>

app/views/wikis/edit.html.erb
<br>
<br>
<br>
<div class="text-center">
	<h1>Edit Wiki Article</h1>
</div>
<br>
  <div class="col-md-2">
    <p>Common policies and guidelines</p>
      <ul>
        <li>Guideline 1</li>
    	  <li>Guideline 2</li>
    	  <li>Guideline 3</li>
    	  <li>Guideline 4</li>
      </ul>
  </div>

  <div class="col-md-7">
  	<%= render 'form' %>
  </div>

app/views/wikis/index.html.erb
<div class="text-center">
	<h1>Blocepedia Library</h1>
</div>

<br>
<br>

  <div class="col-md-7">
  	<% @wikis.each do | wiki | %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  
  <% if user_signed_in? %>
    <div class="col-md-2">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-default' %>
    </div>
  <% end %>

</div>

app/views/wikis/new.html.erb
<br>
<br>
<br>

<div class="text-center">
	<h1>New Wiki Article</h1>
</div>

  <div class="col-md-2">
    <p>Common policies and guidelines</p>
      <ul>
        <li>Guideline 1</li>
    	  <li>Guideline 2</li>
    	  <li>Guideline 3</li>
    	  <li>Guideline 4</li>
      </ul>
  </div>

  <div class="col-md-7">
  	<%= render 'form' %>
  </div>
  

app/views/wikis/show.html.erb
  <div class="col-md-7">
  	<div class="text-center">
  		<h1><%= @wiki.title %></h1>
    </div>
		<h4><%= markdown(@wiki.body) %></h4>
  </div>

  <% if user_signed_in? %>
    <div class="col-md-2">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-default' %>
      <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-default' %>
      <% if policy(@wiki).delete? %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
      <% end %>
    </div>
  <% end %>